site_name: Pyx3270
nav:
  - Início: index.md
  - Comandos X3270: comandos.md
  - Indrodução: introducao.md
  - Changelog: changelog.md
  - Estrutura do Projeto: estrutura.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  language: pt-BR
  highlightjs: true
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      separator: '[\s\-\.]+'
  - towncrier
  - gen-files:
      scripts:
        - docs/gen_tree.py

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/filetree.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
