site_name: Terminal x3270

theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link

plugins: 
  - towncrier

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
