command_map = {
    'abort': ([], 'Aborta scripts e macros pendentes.'),
    'ansitext': ([], 'Exibe texto NVT pendente.'),
    'ascii': ([], 'Conteúdo da tela em ASCII.'),
    'ascii1': (
        [('row', int), ('col', int), [('n', int)]],
        'Bytes da tela em ASCII da posição (1-origem).',
    ),
    'asciifield': ([], 'Conteúdo do campo atual em ASCII.'),
    'attn': ([], 'Envia a sequência ATTN do 3270.'),
    'backspace': ([], 'Move o cursor uma posição para a esquerda.'),
    'backtab': ([], 'Move o cursor para o campo anterior.'),
    'bell': ([], 'Toca o sino do terminal.'),
    'circumnot': ([], 'Envia ~ em NVT ou ¬ em 3270.'),
    'clear': ([], 'Limpa a tela do terminal 3270.'),
    'close': ([], 'Alias para Disconnect, fecha a conexão.'),
    'closescript': ([], 'Encerra o script em execução.'),
    'compose': ([], 'Interpreta as próximas duas teclas conforme o mapa.'),
    'connect': ([('host', str)], 'Conecta ao host.'),
    'cursorselect': ([], 'Seleciona local do cursor como caneta luminosa.'),
    'delete': ([], 'Apaga caractere na posição do cursor.'),
    'deletefield': ([], 'Apaga o conteúdo do campo atual.'),
    'deleteword': ([], 'Apaga a palavra anterior ao cursor.'),
    'disconnect': ([], 'Fecha conexão com o host.'),
    'down': ([], 'Move o cursor para a linha de baixo.'),
    'dup': ([], 'Envia tecla DUP do 3270.'),
    'ebcdic': ([], 'Conteúdo da tela em EBCDIC.'),
    'ebcdicfield': ([], 'Conteúdo do campo atual em EBCDIC.'),
    'enter': ([], 'Envia o comando ENTER.'),
    'erase': ([], 'Backspace destrutivo.'),
    'eraseeof': ([], 'Apaga até o fim do campo.'),
    'eraseinput': ([], 'Apaga todos os campos de entrada.'),
    'escape': ([], 'Abre prompt c3270>'),
    'execute': ([('command', str)], 'Executa comando no shell.'),
    'exit': ([], 'Sai do c3270.'),
    'expect': ([('pattern', str)], 'Aguarda saída NVT.'),
    'fieldend': ([], 'Move cursor ao fim do campo.'),
    'fieldmark': ([], 'Envia tecla FIELD MARK.'),
    'flip': ([], 'Inverte a tela (espelho).'),
    'help': ([('action', str)], 'Exibe ajuda para um tópico.'),
    'hexstring': ([('digits', str)], 'Envia dados em hexadecimal.'),
    'home': ([], 'Move o cursor para o primeiro campo.'),
    'ignore': ([], 'Não faz nada.'),
    'info': ([('text', str)], 'Exibe texto na barra de status (OIA).'),
    'insert': ([], 'Ativa modo de inserção 3270.'),
    'interrupt': ([], 'Envia comando TELNET IAC IP.'),
    'key': ([('symbol', str)], 'Envia um caractere específico.'),
    'keyboarddisable': ([('mode', str)], 'Modifica o bloqueio automático.'),
    'keymap': ([('keymap_name', str)], 'Ativa keymap temporário.'),
    'keypad': ([], 'Mostra o teclado 3270 na tela.'),
    'left': ([], 'Move o cursor 1 coluna à esquerda.'),
    'left2': ([], 'Move o cursor 2 colunas à esquerda.'),
    'macro': ([('name', str)], 'Executa um macro definido.'),
    'menu': ([], 'Exibe o menu de comandos.'),
    'movecursor': (
        [('row', int), ('col', int)],
        'Move cursor para linha e coluna (origem 0).',
    ),
    'movecursor1': (
        [('row', int), ('col', int)],
        'Move cursor para linha e coluna (origem 1).',
    ),
    'movecursoroffset': (
        [('offset', int)],
        'Move cursor para offset na memória.',
    ),
    'newline': ([], 'Move cursor para primeiro campo da linha seguinte.'),
    'nextword': ([], 'Move cursor para a próxima palavra.'),
    'previousword': ([], 'Move cursor para a palavra anterior.'),
    'open': ([], 'Alias para Connect.'),
    'PA': ([('n', int)], 'Envia tecla PA1, PA2, etc.'),
    'PF': ([('n', int)], 'Envia tecla PF1 a PF24.'),
    'pause': ([], 'Espera 350ms.'),
    'paste': ([], 'Cola conteúdo do clipboard.'),
    'printer': (
        [('start', bool), ('lu', str), ('stop', bool)],
        'Inicia ou para sessão de impressão 3287.',
    ),
    'printtext': ([('file', str)], 'Salva ou imprime imagem da tela.'),
    'prompt': ([('app_name', str)], 'Abre prompt externo.'),
    'query': ([('keyword', str)], 'Consulta parâmetros operacionais.'),
    'quit': ([], 'Sai do terminal 3270.'),
    'readbuffer': ([('mode', str)], 'Despeja o buffer de tela.'),
    'reconnect': ([], 'Reconecta ao host anterior.'),
    'redraw': ([], 'Reexibe a tela do terminal.'),
    'reset': ([], 'Desbloqueia o teclado.'),
    'right': ([], 'Move cursor 1 coluna à direita.'),
    'right2': ([], 'Move cursor 2 colunas à direita.'),
    'screentrace': (
        [('mode', str), ('file', str)],
        'Salva imagens da tela em arquivo.',
    ),
    'script': ([('path', str)], 'Executa script filho.'),
    'scroll': ([('direction', str)], 'Rola a tela.'),
    'set': (
        [('setting', str), ('value', str)],
        'Altera ou exibe configurações.',
    ),
    'show': ([('item', str)], 'Exibe status e configurações.'),
    'snap': ([('args', str)], 'Manipula snapshots da tela.'),
    'source': ([('file', str)], 'Executa comandos de um arquivo.'),
    'string': ([('text', str)], 'Envia string para o campo atual.'),
    'sysReq': ([], 'Envia tecla System Request (SysReq).'),
    'tab': ([], 'Move cursor para próximo campo.'),
    'temporarycomposemap': (
        [('map', str)],
        'Define mapa de composição temporário.',
    ),
    'temporarykeymap': ([('keymap_name', str)], 'Alias para Keymap.'),
    'toggle': (
        [('name', str), ('value', str)],
        'Alterna configuração específica.',
    ),
    'toggleinsert': ([], 'Ativa/desativa modo inserção.'),
    'togglereverse': ([], 'Ativa/desativa modo reverso de entrada.'),
    'trace': ([('mode', str)], ('file', str), 'Configura rastreamento.'),
    'transfer': ([('args', str)], 'Transferência de arquivos IND$FILE.'),
    'up': ([], 'Move o cursor para cima.'),
    'wait': ([('args', str | int)], 'Aguarda eventos do host.'),
}
